# Generated by Django 2.1.7 on 2019-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customercollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=120)),
                ('c_email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('c_phone', models.CharField(blank=True, max_length=12)),
                ('c_pswd', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
