# Generated by Django 2.1.7 on 2019-04-07 17:26

from django.db import migrations, models
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=120)),
                ('org_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('gen_id', models.CharField(max_length=15)),
                ('user_type', models.CharField(max_length=200)),
                ('user_acctd', djongo.models.fields.ArrayModelField(model_container=home.models.UserAssociation, model_form_class=home.models.UserAssociationForm)),
            ],
        ),
    ]
